server:
  servlet:
    context-path: /delivery/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://wakanda:NiAVCUsFGBBExp3U@cluster0.djcfb5x.mongodb.net/wakanda?retryWrites=true&w=majority}
      auto-index-creation: true
  main:
    allow-circular-references: true

api:
  security:
    token:
      secret: ${JWT_SECRET:DLPI21D9ITPLAS}

springdoc:
  swagger-ui:
    path: /swagger-ui